### ISSUE TITLE
Enable to share from group view

### ISSUE THREAD

**Issue by jkim485** [sciserver/sciserver-issues-suggestions#1]
From group view it would be nice to be able to share any resource that user has grant privilege without leaving the group site.

**Comment by mikear69** [comment]
This is what Workspaces will do.  We should complete that first, and then see how that could/(or if it should) be adapted to standard Groups.

**Comment by sargas** [comment]
It's the same operation as far as the UI and backend are concerned (since no workspace has privileges assigned, but rather the underlying `UserGroup` has the privileges).

https://github.com/sciserver/resource-management/blob/af463cc6674798228b10cdd668c42f3a000660e8/src/racm/user/controller/UserManagementRESTController.java#L278 is the backend endpoint to do this. For example, to share the volume container with id 4 to the group with id 10, it's just a PUT to `/racm/ugm/rest/groups/10/SharedResources?type=VOLUMECONTAINER&entityId=4&allowedActions=read,write`. The endpoint checks if have the appropriate grant privileges and if you are allowed to share with the workspace's group if applicable (since we have an explicit permission for users to be able to share with workspaces)

Doing this in the dashboard, in general, will require a way to list all the images, database contexts, volume containers, and user volumes that are sharable (the resources tab does not do that, since it deals with RACM `Resource` objects, not the subtly different objects that actually represent these resources. For example, there is no way to get the name of the file service that a volume is in from the endpoint used by the resources tab, despite that being intrinsic to the definition of the user volume).

**Comment by sargas** [comment]
This is now implemented
